{{ config(materialized='view', schema='nibrs_std') }}

with victim_seg as (
    select
        nibrs_year::smallint                                         as nibrs_year,
        trim(segment)                                                as segment,
        trim(state_code)                                             as state_code,
        trim(ori)                                                    as ori,
        trim(incident_no)                                            as incident_no,
        {{ parse_nibrs_date('incident_date') }}                      as incident_date,
        {{ trim_and_stdize_nulls('victim_seq_no') }}::smallint       as victim_seq_no,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense1') }}        as victim_of_ucr_offense1,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense2') }}        as victim_of_ucr_offense2,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense3') }}        as victim_of_ucr_offense3,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense4') }}        as victim_of_ucr_offense4,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense5') }}        as victim_of_ucr_offense5,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense6') }}        as victim_of_ucr_offense6,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense7') }}        as victim_of_ucr_offense7,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense8') }}        as victim_of_ucr_offense8,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense9') }}        as victim_of_ucr_offense9,
        {{ trim_and_stdize_nulls('victim_of_ucr_offense10') }}       as victim_of_ucr_offense10,
        {{ trim_and_stdize_nulls('victim_type') }}                   as victim_type,
        {{ trim_and_stdize_nulls('victim_age') }}                    as victim_age,
        {{ trim_and_stdize_nulls('victim_sex') }}                    as victim_sex,
        {{ trim_and_stdize_nulls('victim_race') }}                   as victim_race,
        {{ trim_and_stdize_nulls('victim_ethnicity') }}              as victim_ethnicity,
        {{ trim_and_stdize_nulls('victim_resident_status') }}        as victim_resident_status,
        {{ trim_and_stdize_nulls('agg_aslt_hom_circumstances1') }}   as agg_aslt_hom_circumstances1,
        {{ trim_and_stdize_nulls('agg_aslt_hom_circumstances2') }}   as agg_aslt_hom_circumstances2,
        {{ trim_and_stdize_nulls('justifiable_hom_circumstances') }} as justifiable_hom_circumstances,
        {{ trim_and_stdize_nulls('victim_injury1_type') }}           as victim_injury1_type,
        {{ trim_and_stdize_nulls('victim_injury2_type') }}           as victim_injury2_type,
        {{ trim_and_stdize_nulls('victim_injury3_type') }}           as victim_injury3_type,
        {{ trim_and_stdize_nulls('victim_injury4_type') }}           as victim_injury4_type,
        {{ trim_and_stdize_nulls('victim_injury5_type') }}           as victim_injury5_type,
        {{ trim_and_stdize_nulls('offender_no_relation1') }}         as offender_no_relation1,
        {{ trim_and_stdize_nulls('victim_offender_relation1') }}     as victim_offender_relation1,
        {{ trim_and_stdize_nulls('offender_no_relation2') }}         as offender_no_relation2,
        {{ trim_and_stdize_nulls('victim_offender_relation2') }}     as victim_offender_relation2,
        {{ trim_and_stdize_nulls('offender_no_relation3') }}         as offender_no_relation3,
        {{ trim_and_stdize_nulls('victim_offender_relation3') }}     as victim_offender_relation3,
        {{ trim_and_stdize_nulls('offender_no_relation4') }}         as offender_no_relation4,
        {{ trim_and_stdize_nulls('victim_offender_relation4') }}     as victim_offender_relation4,
        {{ trim_and_stdize_nulls('offender_no_relation5') }}         as offender_no_relation5,
        {{ trim_and_stdize_nulls('victim_offender_relation5') }}     as victim_offender_relation5,
        {{ trim_and_stdize_nulls('offender_no_relation6') }}         as offender_no_relation6,
        {{ trim_and_stdize_nulls('victim_offender_relation6') }}     as victim_offender_relation6,
        {{ trim_and_stdize_nulls('offender_no_relation7') }}         as offender_no_relation7,
        {{ trim_and_stdize_nulls('victim_offender_relation7') }}     as victim_offender_relation7,
        {{ trim_and_stdize_nulls('offender_no_relation8') }}         as offender_no_relation8,
        {{ trim_and_stdize_nulls('victim_offender_relation8') }}     as victim_offender_relation8,
        {{ trim_and_stdize_nulls('offender_no_relation9') }}         as offender_no_relation9,
        {{ trim_and_stdize_nulls('victim_offender_relation9') }}     as victim_offender_relation9,
        {{ trim_and_stdize_nulls('offender_no_relation10') }}        as offender_no_relation10,
        {{ trim_and_stdize_nulls('victim_offender_relation10') }}    as victim_offender_relation10
    from {{ source('nibrs_raw', 'victim') }}
)

select *
from victim_seg
