version: 2

sources:
  - name: nibrs_raw
    description: "Tables of raw nibrs data."
    schema: nibrs_raw
    tables:
      - name: administrative
      - name: arrest
      - name: arrestee
      - name: batch_header
        columns:
          - name: ori
            tests:
              - not_null
          - name: nibrs_year
            tests:
              - not_null
      - name: batch_header_p1
        columns:
          - name: ori
            tests:
              - not_null
          - name: nibrs_year
            tests:
              - not_null
      - name: batch_header_p2
        columns:
          - name: ori
            tests:
              - not_null
          - name: nibrs_year
            tests:
              - not_null
      - name: batch_header_p3
        columns:
          - name: ori
            tests:
              - not_null
          - name: nibrs_year
            tests:
              - not_null
      - name: offender
      - name: offense
      - name: property
      - name: victim
      - name: window_arrestee
      - name: window_ex_clear
      - name: window_property
