STATE_CODES = {
    "01": "AL",
    "02": "AZ",
    "03": "AR",
    "04": "CA",
    "05": "CO",
    "06": "CT",
    "07": "DE",
    "08": "DC",
    "09": "FL",
    "10": "GA",
    "11": "ID",
    "12": "IL",
    "13": "IN",
    "14": "IA",
    "15": "KS",
    "16": "16",
    "17": "LA",
    "18": "ME",
    "19": "MD",
    "20": "MA",
    "21": "MI",
    "22": "MN",
    "23": "MS",
    "24": "MO",
    "25": "MT",
    "26": "NB",
    "27": "NV",
    "28": "NH",
    "29": "NJ",
    "30": "NM",
    "31": "NY",
    "32": "NC",
    "33": "ND",
    "34": "OH",
    "35": "OK",
    "36": "OR",
    "37": "PA",
    "38": "RI",
    "39": "SC",
    "40": "SD",
    "41": "TN",
    "42": "TX",
    "43": "UT",
    "44": "VT",
    "45": "VA",
    "46": "WA",
    "47": "WV",
    "48": "WI",
    "49": "WY",
    "50": "AK",
    "51": "HI",
    "52": "CZ",
    "53": "PR",
    "54": "AS",
    "55": "GM",
    "62": "VI",
}

POP_GROUP = {
    "0": "Possessions (PR, Guam, Canal Zone, VI, AS)",
    "1": "All cities 250K or over",
    "1A": "Cities 1M or over",
    "1B": "Cities from 500K thru 999999",
    "1C": "Cities from 250K thru 499999",
    "2": "Cities from 100K thru 249999",
    "3": "Cities from 50K thru 99999",
    "4": "Cities from 25K thru 49999",
    "5": "Cities from 10K thru 24999",
    "6": "Cities from 2500 thru 9999",
    "7": "Cities under 2500",
    "8": "Non-MSA Counties",
    "8A": "Non-MSA Counties 100K or over",
    "8B": "Non-MSA Counties from 25K thru 99999",
    "8C": "Non-MSA Counties from 10K thru 24999",
    "8D": "Non-MSA Counties under 10K",
    "9": "MSA Counties",
    "9A": "MSA Counties 100K or over",
    "9B": "MSA Counties from 25K thru 99999",
    "9C": "MSA Counties from 10K thru 24999",
    "9D": "MSA Counties under 10K",
    "9E": "MSA State Police",
}

DIVISION = {
    "0": "Possessions",
    "1": "New England",
    "2": "Middle Atlantic",
    "3": "East North Central",
    "4": "West North Central",
    "5": "South Atlantic",
    "6": "East South Central",
    "7": "West South Central",
    "8": "Mountain",
    "9": "Pacific",
}

REGION = {
    "1": "North East",
    "2": "North Central",
    "3": "South",
    "4": "West",
}

AGENCY_IND = {
    "0": "Covered by Another Agency",
    "1": "City",
    "2": "County",
    "3": "University of College",
    "4": "State Police",
}

EX_CLEARED_CODES = {
    "A": "Death of the offender",
    "B": "Prosecution declined (for other than lack of probable cause)",
    "C": "Extradition denied",
    "D": "Victim refused to cooperate",
    "E": "Juvenile/no custody",
    "N": "Not applicable",
}

UCR_OFFENSE_CODES = {
    "09A": "Murder/Nonnegligent Manslaughter",
    "09B": "Negligent Manslaughter",
    "09C": "Justifiable Homicide",
    "100": "Kidnapping/Abduction",
    "11A": "Forcible Rape",
    "11B": "Forcible Sodomy",
    "11C": "Sexual Assault With An Object",
    "11D": "Forcible Fondling (Indecent Liberties/Child Molest)",
    "120": "Robbery",
    "13A": "Aggravated Assault",
    "13B": "Simple Assault",
    "13C": "Intimidation",
    "200": "Arson",
    "210": "Extortion/Blackmail",
    "220": "Burglary/Breaking and Entering",
    "23A": "Pocket Picking",
    "23B": "Purse Snatching",
    "23C": "Shoplifting",
    "23D": "Theft From Building",
    "23E": "Theft From Coin-Operated Machine/Device",
    "23F": "Theft From Motor Vehicle",
    "23G": "Theft Of Motor Vehicle Parts/Accessories",
    "23H": "All Other Larceny",
    "240": "Motor Vehicle Theft",
    "250": "Counterfeiting/Forgery",
    "26A": "False Pretenses/Swindle/Confidence Game",
    "26B": "Credit Card/Automatic Teller Machine Fraud",
    "26C": "Impersonation",
    "26D": "Welfare Fraud",
    "26E": "Wire Fraud",
    "270": "Embezzlement",
    "280": "Stolen Property Offenses (Receiving, Selling, Etc)",
    "290": "Destruction/Damage/Vandalism of Property",
    "35A": "Drug/Narcotic Violations",
    "35B": "Drug Equipment Violations",
    "36A": "Incest - Nonforcible",
    "36B": "Statutory Rape - Nonforcible",
    "370": "Pornography/Obscene Material",
    "39A": "Betting/Wagering",
    "39B": "Operating/Promoting/Assisting Gambling",
    "39C": "Gambling Equipment Violations",
    "39D": "Sports Tampering",
    "40A": "Prostitution",
    "40B": "Assisting or Promoting Prostitution",
    "510": "Bribery",
    "520": "Weapon Law Violations",
    "90A": "Bad Checks",
    "90B": "Curfew/Loitering/Vagrancy Violation",
    "90C": "Disorderly Conduct",
    "90D": "Driving Under the Influence",
    "90E": "Drunkenness",
    "90F": "Family Offenses, Nonviolent",
    "90G": "Liquor Law Violations",
    "90H": "Peeping Tom",
    "90I": "Runaway",
    "90J": "Trespass of Real Property",
    "90Z": "All Other Offenses",
}

SUSPECTED_OF_USING_CODES = {
    "A": "Alcohol",
    "C": "Computer Equipment",
    "D": "Drugs/Narcotics",
    "N": "Not applicable",
}

LOCATION_TYPE_CODES = {
    "01": "Air/Bus/Train Terminal",
    "02": "Bank/Savings and Loan",
    "03": "Bar/Nightclub",
    "04": "Church/Synagogue/Temple",
    "05": "Commercial/Office Building",
    "06": "Construction Site",
    "07": "Convenience Store",
    "08": "Department/Discount Store",
    "09": "Drug Store/Dr's Office/Hospital",
    "10": "Field/Woods",
    "11": "Government/Public Building",
    "12": "Grocery/Supermarket",
    "13": "Highway/Road/Alley",
    "14": "Hotel/Motel/Etc",
    "15": "Jail/Prison",
    "16": "Lake/Waterway",
    "17": "Liquor Store",
    "18": "Parking Lot/Garage",
    "19": "Rental Storage Facility",
    "20": "Residence/Home",
    "21": "Restaurant",
    "22": "School/College",
    "23": "Service/Gas Station",
    "24": "Specialty Store (TV, Fur, Etc)",
    "25": "Other/Unknown",
}

CRIMINAL_ACTIVITY_TYPES = {
    "B": "Buying/Receiving",
    "C": "Cultivating/Manufacturing/Publishing",
    "D": "Distributing/Selling",
    "E": "Exploiting Children",
    "O": "Operating/Promoting/Assisting",
    "P": "Possessing/Concealing",
    "T": "Transporting/Transmitting/Importing",
    "U": "Using/Consuming",
}

BIAS_MOTIVATION_CODES = {
    "11": "White",
    "12": "Black",
    "13": "American Indian or Alaskan Native",
    "14": "Asian/Pacific Islander",
    "15": "Multi-Racial Group",
    "21": "Jewish",
    "22": "Catholic",
    "23": "Protestant",
    "24": "Islamic (Moslem)",
    "25": "Other Religion",
    "26": "Multi-Religious Group",
    "27": "Atheism/Agnosticism",
    "31": "Arab",
    "32": "Hispanic",
    "33": "Other Ethnicity/Natl. Origin",
    "41": "Male Homosexual (Gay)",
    "42": "Female Homosexual (Lesbian)",
    "43": "Homosexual (Gay and Lesbian)",
    "44": "Heterosexual",
    "45": "Bisexual",
    "88": "None",
    "99": "Unknown",
}

PROPERTY_LOSS_TYPE_CODES = {
    "1": "None",
    "2": "Burned",
    "3": "Counterfeited/Forged",
    "4": "Destroyed/Damaged/Vandalized",
    "5": "Recovered",
    "6": "Seized",
    "7": "Stolen/Etc (includes bribed, defrauded, embezzled, extorted, ransomed, robbed, etc)",
    "8": "Unknown",
}

PROPERTY_DESCR_CODES = {
    "01": "Aircraft",
    "02": "Alcohol",
    "03": "Automobiles",
    "04": "Bicycles",
    "05": "Buses",
    "06": "Clothes/Furs",
    "07": "Computer Hardware/Software",
    "08": "Consumable Goods",
    "09": "Credit/Debit Cards",
    "10": "Drugs/Narcotics",
    "11": "Drug/Narcotic Equip",
    "12": "Farm Equipment",
    "13": "Firearms",
    "14": "Gambling Equipment",
    "15": "Heavy Construction/Industrial Equipment",
    "16": "Household Goods",
    "17": "Jewelry/Precious Metals",
    "18": "Livestock",
    "19": "Merchandise",
    "20": "Money",
    "21": "Negotiable Instruments",
    "22": "Nonnegotiable Instruments",
    "23": "Office-Type Equipment",
    "24": "Other Motor Vehicles",
    "25": "Purses/Handbags/Wallets",
    "26": "Radios/TVs/VCRs",
    "27": "Recordings - Audio/Visual",
    "28": "Recreational Vehicles",
    "29": "Structures-Single Occupancy Dwellings",
    "30": "Structures-Other Dwellings",
    "31": "Structures - Commercial/Business",
    "32": "Structures - Industrial/Manufacturing",
    "33": "Structures - Public/Community",
    "34": "Structures - Storage",
    "35": "Structures - Other",
    "36": "Tools-Power/Hand",
    "37": "Trucks",
    "38": "Vehicle Parts/Accessories",
    "39": "Watercraft",
    "77": "Other",
    "88": "Pending Inventory (of Property)",
    "99": "Special Category",
}

SUSPECTED_DRUG_TYPE_CODE = {
    "A": "Crack Cocaine",
    "B": "Cocaine (all forms except Crack)",
    "C": "Hashish",
    "D": "Heroin",
    "E": "Marijuana",
    "F": "Morphine",
    "G": "Opium",
    "H": "Other Narcotics",
    "I": "LSD",
    "J": "PCP",
    "K": "Other Hallucinogens",
    "L": "Amphetamines/Methamphetamines",
    "M": "Other Stimulants",
    "N": "Barbiturates",
    "O": "Other Depressants",
    "P": "Other Drugs",
    "U": "Unknown Type Drug",
    "X": "Over 3 Drug Types",
}

VICTIM_TYPE_CODES = {
    "I": "Individual",
    "B": "Business",
    "F": "Financial Institution",
    "G": "Government",
    "R": "Religious Organization",
    "S": "Society/Public",
    "O": "Other",
    "U": "Unknown",
}

VICTIM_AGE_CODES = {
    "NN": "Under 24 Hours (neonate)",
    "NB": "1-6 Days Old",
    "BB": "7-364 Days Old",
    "00": "Unknown",
    "01-98": "Age in Years",
    "99": "Over 98 Years Old",
}

SEX_CODES = {
    "M": "Male",
    "F": "Female",
    "U": "Unknown",
}

RACE_CODES = {
    "W": "White",
    "B": "Black",
    "I": "American Indian/Alaskan Native",
    "A": "Asian/Pacific Islander",
    "U": "Unknown",
}

ETHNICITY_CODES = {
    "H": "Hispanic origin",
    "N": "Not of Hispanic origin",
    "U": "Unknown",
}

VICTIM_RESIDENCY_STATUS_CODES = {
    "R": "Resident",
    "N": "Nonresident",
    "U": "Unknown",
}

AGG_ASSAULT_HOM_CIRCUMSTANCE_CODES = {
    "01": "Argument",
    "02": "Assault on Law Enf. Officer(s)",
    "03": "Drug Dealing",
    "04": "Gangland",
    "05": "Juvenile Gang",
    "06": "Lovers' Quarrel",
    "07": "Mercy Killing (Not applicable to Aggrav. Assault)",
    "08": "Other Felony Involved",
    "09": "Other Circumstances",
    "10": "Unknown Circumstances",
    "30": "Child Playing With Weapon",
    "31": "Gun-Cleaning Accident",
    "32": "Hunting Accident",
    "33": "Other Negligent Weapon Handling",
    "34": "Other Negligent Killings",
    "20": "Criminal Killed by Private Citizen",
    "21": "Criminal Killed by Police Officer",
}

JUSTIFIABLE_HOMICIDE_CIRCUMSTANCE_CODES = {
    "A": "Criminal Attacked Police Officer and That Officer Killed Criminal",
    "B": "Criminal Attacked Fellow Police Officer and Criminal Killed by Another Police Officer",
    "C": "Criminal Attacked a Civilian",
    "D": "Criminal Attempted Flight From a Crime",
    "E": "Criminal Killed In Commission of a Crime",
    "F": "Criminal Resisted Arrest",
    "G": "Unable to Determine/Not Enough Information",
}

INJURY_TYPE_CODES = {
    "N": "None",
    "M": "Apparent Minor Injury",
    "B": "Apparent Broken Bones",
    "O": "Other Major Injury",
    "I": "Possible Internal Injury",
    "T": "Loss of Teeth",
    "L": "Severe Laceration",
    "U": "Unconsciousness",
}

VICTIM_OFFENDER_RELATIONSHIP_CODES = {
    "SE": "Victim was Spouse",
    "CS": "Victim was Common-Law Spouse",
    "PA": "Victim was Parent",
    "SB": "Victim was Sibling",
    "CH": "Victim was Child",
    "GP": "Victim was Grandparent",
    "GC": "Victim was Grandchild",
    "IL": "Victim was In-Law",
    "SP": "Victim was Stepparent",
    "SC": "Victim was Stepchild",
    "SS": "Victim was Stepsibling",
    "OF": "Victim was Other Family Member",
    "VO": "Victim was Offender",
    "AQ": "Victim was Acquaintance",
    "FR": "Victim was Friend",
    "NE": "Victim was Neighbor",
    "BE": "Victim was Babysittee (the baby)",
    "BG": "Victim was Boyfriend/Girlfriend",
    "CF": "Victim was Child of Boyfriend/Girlfriend",
    "HR": "Homosexual Relationship",
    "XS": "Victim was Ex-Spouse",
    "EE": "Victim was Employee",
    "ER": "Victim was Employer",
    "OK": "Victim was Otherwise Known",
    "RU": "Relationship Unknown",
    "ST": "Victim was Stranger",
}

ARREST_TYPE_CODES = {
    "O": "On-View Arrest (taken into custody without a warrant or previous incident report)",
    "S": "Summoned/Cited (not taken into custody)",
    "T": "Taken Into Custody (based on warrant and/or previous incident report)",
}

ARRESTEE_ARMED_WITH_CODES = {
    "01": "Unarmed",
    "11": "Firearm (type not stated)",
    "12": "Handgun",
    "13": "Rifle",
    "14": "Shotgun",
    "15": "Other Firearm",
    "16": "Lethal Cutting Instrument (e.g., switchblade knife, etc.)",
    "17": "Club/Blackjack/Brass Knuckles",
}
