fbi_dbt:
  target: prod
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DATABASE_PATH', '../data/databases/dev_cde_dwh.duckdb') }}"
      threads: 4

    prod:
      type: duckdb
      path: "{{ env_var('DBT_DATABASE_PATH', '../data/databases/cde_dwh.duckdb') }}"
      threads: 4
